# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='password',
            field=models.CharField(default=1234, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authormodel',
            name='username',
            field=models.CharField(default=123456, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
