# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181019_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authormodel',
            name='user',
        ),
    ]
