# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 05:53
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_authormodel_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authormodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
