# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20181019_0553'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authormodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='username',
        ),
        migrations.AddField(
            model_name='authormodel',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
